number = 4
title = "Getting started"

[[article]]
file = "overview.md"
title = "Overview"
author = "zine-team"
cover = "/static/sky.jpg"
pub_date = "2022-11-30"
publish = true
featured = true

[[article]]
file = "installation.md"
title = "Installation"
author = "zine-team"
cover = "/static/sky.jpg"
pub_date = "2022-11-30"
publish = true
featured = true

[[article]]
file = "directory-structure.md"
title = "Directory Structure"
author = "zine-team"
cover = "/static/sky.jpg"
topic = ["article", "issue"]
pub_date = "2022-11-30"
publish = true
featured = true
