number = 2
title = "Customization"

[[article]]
file = "theme.md"
title = "Theme"
author = "zine-team"
cover = ""
pub_date = "2022-11-30"
publish = true
featured = true

[[article]]
file = "css.md"
title = "Customize CSS styles"
author = "zine-team"
cover = ""
pub_date = "2022-11-30"
publish = true
featured = true
