number = 1
title = "Advanced"

[[article]]
file = "pages.md"
title = "Pages"
author = "zine-team"
cover = "/static/sky5.jpg"
pub_date = "2022-11-30"
publish = true
featured = true

[[article]]
file = "l10n.md"
title = "Localization"
author = "zine-team"
cover = "/static/sky5.jpg"
pub_date = "2022-11-30"
publish = true
featured = true

[[article]]
file = "i18n.md"
title = "Internationalization"
author = "zine-team"
cover = "/static/sky5.jpg"
pub_date = "2022-11-30"
publish = true
featured = true
