number = 2
title = "Code blocks"

[[article]]
file = "url-preview.md"
title = "Url preview"
author = "zine-team"
cover = "/static/sky6.jpg"
pub_date = "2022-11-30"
publish = true
featured = true

[[article]]
file = "callout.md"
title = "Callout"
author = "zine-team"
cover = "/static/sky6.jpg"
pub_date = "2022-11-30"
publish = true
featured = true

[[article]]
file = "quote.md"
title = "Quote"
author = "zine-team"
cover = "/static/sky6.jpg"
pub_date = "2022-11-30"
publish = true
featured = true

[[article]]
file = "article.md"
title = "Article"
author = "zine-team"
cover = "/static/sky6.jpg"
pub_date = "2022-11-30"
publish = true
featured = true

[[article]]
file = "author.md"
title = "Author"
author = "zine-team"
cover = "/static/sky6.jpg"
pub_date = "2022-11-30"
publish = true
featured = true
